{% set version = "0.5.4" %}

package:
  name: datashape
  version: {{ version }}

source:
  url: https://github.com/blaze/datashape/archive/{{ version }}.tar.gz
  sha256: c266c5803dde48b9fa8d8ee51b5b5979ef77443060e32db2d225b72648c638a5

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.7
    - multipledispatch >=0.4.7
    - python-dateutil

test:
  imports:
    - datashape
    - datashape.tests
    - datashape.util
  requires:
    - pytest 3.10.1
    - mock
    - numpy 1.11
  commands:
    - pytest -vx --doctest-modules --pyargs datashape

about:
  home: http://datashape.pydata.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: 'A data description language'
  license_family: BSD
  description: |
    Datashape is a data layout language for array programming.
    It is designed to describe in-situ structured data without requiring
    transformation into a canonical form.
  doc_url: http://datashape.readthedocs.org/en/latest
  doc_source_url: https://github.com/blaze/datashape/blob/master/docs/source/index.rst
  dev_url: https://github.com/blaze/datashape

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
