appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aCyLDLAQ8ZXZ1h/ekG7FnNdQ2ONF+CNaxjsAl0xYhKOLoAGvVvwC9RlJqLLaS8wSRrxWRkAfLi5tsGWfQts9+OYCe18ja4a9hK9rdJW78Gq8YUFLD0zLGD1A3o6V58gkxXlvSoxXgh/MPQ+vlNe+tVHUVOELI9f5f+QaJMAb1EftpEOlhWEebWhx8Qt502DjCQa2XaMJCkJAbwCJArjJQydfuC3dMZiRC5UtHZUeAMB7vWQk1tVTbB1NtV/44/0RiJkaCISToU1g9ze+NB6t2mrSYX7J5K+4Zc3s5R2B5WIn35+BweShtnpxc0PEUTSphyrDrWjoSwpXn0+Nkw4aaq4G31UEmj4o3tKNZYFpqMkIepuoKn6afLUlQ27Bmbz0mWcqFviwZq+qLwBx7QJ1IaM5kcguIJC9r+oecGRw0AiVQT1vv2gdJg0JRdwOTOyCj33jHbX8uh6DZ04wAfpT/EyCHBB7nwyTzOX13qnxleXhiyxFDoj5we2nRHm9quOAgZjvjjIQqnvvUz8O4CwtMSaBAsL8sk0qVFbPD9QqWxz7ipJYAO1XVn2BfifnD2WJ13wzYiAbnLCCGywuztb3wAP7ArTr1by6gIDKFtjYPiMgTekkAHn8v6JD0hjBkDKH2Q7ZT/xqaXewKJLiz5XN3risXNd3iA7FVx/YUoFt/WE=}
