travis:
  secure:
    BINSTAR_TOKEN: aNKVjMjIq1o8M8gG1qSNS+DYP8qbAY9ia6cPCax6Hiik9hhQOKjKsprYvfHQuncRLI9QL/BVvVtGFW0B2exJGyDY14yzcsxhDJBEUq9DepGtyQBZOiuahboACflM6yxdSD7uWdAM/LT20MBsX/u/vP9AS9ULqWsqq0ACF7x40w283VHzwZl6df6vbEPOh2ibU0XJrDafzYEgATh9Hr3LooxDTXbUHoX8qJ4jfA0yl7zh5L1Bjkkuw/I6y5w+I5QDCSUdba8eLMnidio0lM8OVHHbp9sh/dtbHlj5I6P1YtFLAJgCwjeruod2ypyGq/woh6dZjsOzxoXbvxkGXybRKyDh/3+bnQ0gDtGbDb17dDbGQmhiGVCLe6va+bCxNx8noz0aK5qDaCZnjRP5f5e+1jd/EhKkcvC4JCcqDskN6hLiwoRAcqF1c7JyLVup/0y9hy+zUCYbCG/y0lqfvRuZHkxuHChckXzgMB5ynCgl6NI3cwGusNcLu2aQy99w04isV5GNf6Mp0eqx+EWoE2vsIJ6CZfCQdJzQ9p53/75/axg0G/rsdUl4ZFJ9v+gw3xmrT6e6HJw5FnlNFFofz2GGshCn796VV70p0H32I3ZZEPRB1s/XnvGOVfixV/yZSOsIKI4I4d7XfX/v4ViVKSZTT8MKMe0wDChQjiNxtTpVOBo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
